language: rust
rust:
- nightly
- beta
- stable
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  ln -s /bin/rustdoc $HOME/.local/bin/rustdoc &&
  export PATH=$HOME/.local/bin
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  rustdoc --test README.md -L dependency=./target/debug/deps --extern rustc_version=./target/debug/librustc_version.rlib &&
  travis-cargo bench &&
  travis-cargo --only stable doc
after_success:
- travis-cargo --only stable doc-upload
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
